<a href="https://colab.research.google.com/github/udisinghania/500-Person-Gender-Height-Weight-Body-Mass-Index/blob/master/500_Person_Gender_Height_Weight_Body_Mass_Index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import files


In [2]:
files.upload()

Saving 500_Person_Gender_Height_Weight_Index.csv to 500_Person_Gender_Height_Weight_Index (1).csv


{'500_Person_Gender_Height_Weight_Index.csv': b'Gender,Height,Weight,Index\r\nMale,174,96,4\r\nMale,189,87,2\r\nFemale,185,110,4\r\nFemale,195,104,3\r\nMale,149,61,3\r\nMale,189,104,3\r\nMale,147,92,5\r\nMale,154,111,5\r\nMale,174,90,3\r\nFemale,169,103,4\r\nMale,195,81,2\r\nFemale,159,80,4\r\nFemale,192,101,3\r\nMale,155,51,2\r\nMale,191,79,2\r\nFemale,153,107,5\r\nFemale,157,110,5\r\nMale,140,129,5\r\nMale,144,145,5\r\nMale,172,139,5\r\nMale,157,110,5\r\nFemale,153,149,5\r\nFemale,169,97,4\r\nMale,185,139,5\r\nFemale,172,67,2\r\nFemale,151,64,3\r\nMale,190,95,3\r\nMale,187,62,1\r\nFemale,163,159,5\r\nMale,179,152,5\r\nMale,153,121,5\r\nMale,178,52,1\r\nFemale,195,65,1\r\nFemale,160,131,5\r\nFemale,157,153,5\r\nFemale,189,132,4\r\nFemale,197,114,3\r\nMale,144,80,4\r\nFemale,171,152,5\r\nFemale,185,81,2\r\nFemale,175,120,4\r\nFemale,149,108,5\r\nMale,157,56,2\r\nMale,161,118,5\r\nFemale,182,126,4\r\nMale,185,76,2\r\nFemale,188,122,4\r\nMale,181,111,4\r\nMale,161,72,3\r\nMale,140,152,5\

In [0]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [0]:
train = pd.read_csv('./500_Person_Gender_Height_Weight_Index.csv')


In [5]:
train.head()

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
Gender    500 non-null object
Height    500 non-null int64
Weight    500 non-null int64
Index     500 non-null int64
dtypes: int64(3), object(1)
memory usage: 15.7+ KB


In [0]:
train = pd.get_dummies(train, columns=train.select_dtypes('object').columns)

In [8]:
train.head()

Height  Weight  Index  Gender_Female  Gender_Male
0     174      96      4              0            1
1     189      87      2              0            1
2     185     110      4              1            0
3     195     104      3              1            0
4     149      61      3              0            1

In [0]:
y = train.loc[:,'Index']
X = train.drop('Index', axis=1)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[ 0.24793878, -0.30911702, -1.02020406,  1.02020406],
       [ 1.16487212, -0.58732233, -1.02020406,  1.02020406],
       [ 0.92035656,  0.12364681,  0.98019606, -0.98019606],
       ...,
       [-1.76931458,  0.92735105,  0.98019606, -0.98019606],
       [-1.21915457, -0.34002872, -1.02020406,  1.02020406],
       [ 0.18680989,  0.77279254, -1.02020406,  1.02020406]])

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [12]:
print('Training Features Shape:', X_train.shape)
print('Training Labels Shape:', y_train.shape)
print('Testing Features Shape:', X_test.shape)
print('Testing Labels Shape:', y_test.shape)

Training Features Shape: (375, 4)
Training Labels Shape: (375,)
Testing Features Shape: (125, 4)
Testing Labels Shape: (125,)


In [0]:
from sklearn.naive_bayes import GaussianNB
s = GaussianNB()
clf = s.fit(X_train,y_train)

In [0]:
y_pred = s.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.728

In [0]:
from sklearn import tree
s = tree.DecisionTreeClassifier()
clf = s.fit(X_train,y_train)

In [0]:
y_pred = s.predict(X_test)

In [18]:
accuracy_score(y_test, y_pred)

0.832

In [19]:
from keras import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [20]:
len(X_train[0])

4

In [0]:
classifier = Sequential()

classifier.add(Dense(4,activation = 'relu', kernel_initializer = 'random_normal', input_dim=4))

classifier.add(Dense(3,activation = 'relu', kernel_initializer = 'random_normal'))

classifier.add(Dense(3,activation = 'sigmoid', kernel_initializer = 'random_normal'))

classifier.add(Dense(1,activation = 'relu', kernel_initializer = 'random_normal'))

In [0]:
classifier.compile(optimizer='adam',loss='mse',metrics=['accuracy'])


In [45]:
classifier.fit(X_train,y_train, batch_size=10, epochs=100)


Epoch 1/100
375/375 [==============================] - 0s 156us/step - loss: 1.3542 - acc: 0.1813
Epoch 2/100
375/375 [==============================] - 0s 116us/step - loss: 1.2690 - acc: 0.2720
Epoch 3/100
375/375 [==============================] - 0s 158us/step - loss: 1.1894 - acc: 0.3413
Epoch 4/100
375/375 [==============================] - 0s 138us/step - loss: 1.1101 - acc: 0.3920
Epoch 5/100
375/375 [==============================] - 0s 132us/step - loss: 1.0369 - acc: 0.4000
Epoch 6/100
375/375 [==============================] - 0s 140us/step - loss: 0.9674 - acc: 0.4267
Epoch 7/100
375/375 [==============================] - 0s 150us/step - loss: 0.9020 - acc: 0.4320
Epoch 8/100
375/375 [==============================] - 0s 171us/step - loss: 0.8450 - acc: 0.4400
Epoch 9/100
375/375 [==============================] - 0s 163us/step - loss: 0.8001 - acc: 0.4560
Epoch 10/100
375/375 [==============================] - 0s 134us/step - loss: 0.7612 - acc: 0.4613
Epoch 11/100
375/37

In [46]:

eval_model=classifier.evaluate(X_train, y_train)
eval_model

375/375 [==============================] - 0s 673us/step


[0.17258367164929708, 0.8586666655540466]

In [0]:
y_pred=classifier.predict(X_test)

In [0]:
q = []
for i in y_pred:
  q.append(int(round(i[0])))

In [68]:
q

[5,
 2,
 3,
 4,
 5,
 5,
 5,
 5,
 3,
 5,
 4,
 5,
 2,
 5,
 5,
 3,
 5,
 5,
 3,
 5,
 2,
 5,
 1,
 4,
 4,
 5,
 5,
 5,
 5,
 2,
 5,
 5,
 4,
 4,
 4,
 2,
 5,
 2,
 4,
 2,
 5,
 2,
 4,
 3,
 5,
 4,
 3,
 4,
 4,
 4,
 5,
 4,
 2,
 1,
 5,
 2,
 2,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 1,
 2,
 3,
 4,
 2,
 2,
 2,
 5,
 2,
 3,
 5,
 5,
 5,
 4,
 2,
 5,
 5,
 3,
 2,
 5,
 4,
 5,
 3,
 5,
 5,
 3,
 1,
 2,
 5,
 4,
 5,
 2,
 5,
 5,
 1,
 5,
 4,
 5,
 5,
 5,
 3,
 3,
 4,
 5,
 4,
 5,
 3,
 4,
 3,
 3,
 2,
 5,
 5,
 5,
 5,
 2,
 3,
 4,
 4,
 5,
 4]

In [69]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, q)
print(cm)

[[ 0  1  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0  0 20  3  1  0]
 [ 0  0  2  8  0  0]
 [ 0  0  0  6 25  7]
 [ 0  0  0  0  0 48]]
